REGIONS = {
    "global": {
        "name": "Global",
        "west": -180,
        "east": 180,
        "south": -90,
        "north": 90,
        "central_longitude": 0,
        "central_latitude": 0,
        "projection": "platecarree",
    },

    "conus": {
        "name": "CONUS",
        "west": -125,
        "east": -66,
        "south": 24,
        "north": 50,
        "central_longitude": -96,
        "central_latitude": 38,
        "projection": "lambert",
    },

    "north_america": {
        "name": "North America",
        "west": -170,
        "east": -50,
        "south": 10,
        "north": 75,
        "central_longitude": -100,
        "central_latitude": 45,
        "projection": "lambert",
    },

    "northeast": {
        "name": "Northeast",
        "west": -82,
        "east": -65,
        "south": 36,
        "north": 48,
        "central_longitude": -73.5,
        "central_latitude": 42,
        "projection": "lambert",
    },

    "new_england": {
        "name": "New England",
        "west": -74,
        "east": -66,
        "south": 40,
        "north": 48,
        "central_longitude": -70,
        "central_latitude": 44,
        "projection": "lambert",
    },

    "atlantic": {
        "name": "Atlantic Ocean",
        "west": -100,
        "east": 20,
        "south": -60,
        "north": 75,
        "central_longitude": -40,
        "central_latitude": 10,
        "projection": "platecarree",
    },

    "western_atlantic": {
        "name": "Western Atlantic",
        "west": -100,
        "east": -45,
        "south": -10,
        "north": 60,
        "central_longitude": -70,
        "central_latitude": 25,
        "projection": "lambert",
    },

    "central_atlantic": {
        "name": "Central Atlantic",
        "west": -60,
        "east": -20,
        "south": -20,
        "north": 50,
        "central_longitude": -40,
        "central_latitude": 15,
        "projection": "platecarree",
    },

    "eastern_atlantic": {
        "name": "Eastern Atlantic",
        "west": -40,
        "east": 20,
        "south": -20,
        "north": 60,
        "central_longitude": -10,
        "central_latitude": 20,
        "projection": "platecarree",
    },

    "tropical_atlantic": {
        "name": "Tropical Atlantic",
        "west": -100,
        "east": 10,
        "south": 0,
        "north": 35,
        "central_longitude": -45,
        "central_latitude": 18,
        "projection": "platecarree",
    },

    "caribbean": {
        "name": "Caribbean",
        "west": -90,
        "east": -55,
        "south": 8,
        "north": 30,
        "central_longitude": -72,
        "central_latitude": 19,
        "projection": "platecarree",
    },

    "europe": {
        "name": "Europe",
        "west": -25,
        "east": 45,
        "south": 30,
        "north": 72,
        "central_longitude": 10,
        "central_latitude": 50,
        "projection": "lambert",
    },

    "north_pacific": {
        "name": "North Pacific",
        "west": 120,
        "east": -100,
        "south": 10,
        "north": 70,
        "central_longitude": 180,
        "central_latitude": 35,
        "projection": "platecarree",
    },

    "eastern_pacific": {
        "name": "Eastern Pacific",
        "west": -180,
        "east": -80,
        "south": -20,
        "north": 60,
        "central_longitude": -130,
        "central_latitude": 20,
        "projection": "platecarree",
    },

    "western_pacific": {
        "name": "Western Pacific",
        "west": 100,
        "east": 180,
        "south": -20,
        "north": 60,
        "central_longitude": 140,
        "central_latitude": 20,
        "projection": "platecarree",
    },

    "tropical_pacific": {
        "name": "Tropical Pacific",
        "west": 100,
        "east": -70,
        "south": -30,
        "north": 30,
        "central_longitude": 180,
        "central_latitude": 0,
        "projection": "platecarree",
    },

    "indian_ocean": {
        "name": "Indian Ocean",
        "west": 20,
        "east": 130,
        "south": -50,
        "north": 35,
        "central_longitude": 75,
        "central_latitude": -5,
        "projection": "platecarree",
    },

    "western_indian_ocean": {
        "name": "Western Indian Ocean",
        "west": 20,
        "east": 80,
        "south": -45,
        "north": 30,
        "central_longitude": 50,
        "central_latitude": -5,
        "projection": "platecarree",
    },

    "central_indian_ocean": {
        "name": "Central Indian Ocean",
        "west": 50,
        "east": 100,
        "south": -45,
        "north": 30,
        "central_longitude": 75,
        "central_latitude": -5,
        "projection": "platecarree",
    },

    "eastern_indian_ocean": {
        "name": "Eastern Indian Ocean",
        "west": 80,
        "east": 125,
        "south": -45,
        "north": 25,
        "central_longitude": 102,
        "central_latitude": -10,
        "projection": "platecarree",
    },

    "arctic": {
        "name": "Arctic",
        "west": -180,
        "east": 180,
        "south": 50,
        "north": 90,
        "central_longitude": 0,
        "central_latitude": 90,
        "projection": "north_polar",
    },

    "southern_ocean": {
        "name": "Southern Ocean",
        "west": -180,
        "east": 180,
        "south": -90,
        "north": -40,
        "central_longitude": 0,
        "central_latitude": -90,
        "projection": "south_polar",
    },
}