import csv
import io
from pathlib import Path

from .track_schema import FNV3TrackPoint


# ============================================================
# BASIC CONVERSION
# ============================================================

def _optional_float(value):
    if value is None:
        return None

    value = str(value).strip()

    if not value:
        return None

    try:
        return float(value)
    except ValueError:
        return None


def _required_float(value):
    return float(
        str(value).strip()
    )


def _required_int(value):
    return int(
        float(
            str(value).strip()
        )
    )


# ============================================================
# TRACK IDENTIFICATION
# ============================================================

def _is_generated_track(track_id):
    """
    Weather Lab cyclogenesis output uses numeric track IDs
    for model-generated/unpaired cyclogenesis systems.

    Existing initialized systems use identifiers such as:
        AL952026
        EP092026
        WP172026
    """

    return str(
        track_id
    ).strip().isdigit()


def _normalize_system_id(track_id):
    """
    Make model-generated systems obvious throughout the
    MassachusettsWx pipeline.

    Examples
    --------
    11       -> GEN11
    4        -> GEN4
    AL952026 -> AL952026
    """

    track_id = str(
        track_id
    ).strip()

    if _is_generated_track(
        track_id
    ):
        return (
            f"GEN{track_id}"
        )

    return track_id


# ============================================================
# WEATHER LAB CYCLOGENESIS CSV
# ============================================================

def parse_weatherlab_cyclogenesis_csv(text):
    """
    Parse Google Weather Lab's unpaired WeatherNext Cyclones
    Operational cyclogenesis CSV.

    Unique tracks are represented downstream by:

        (system_id, member)

    This is important because numeric track IDs may be reused
    in different ensemble members.

    Parameters
    ----------
    text : str
        Full Weather Lab cyclogenesis CSV, including optional
        leading # comment/license lines.

    Returns
    -------
    list[FNV3TrackPoint]
    """

    data_lines = []

    for raw_line in text.splitlines():
        if raw_line.startswith("#"):
            continue

        if not raw_line.strip():
            continue

        data_lines.append(
            raw_line
        )

    if not data_lines:
        return []

    reader = csv.DictReader(
        io.StringIO(
            "\n".join(
                data_lines
            )
        )
    )

    output = []

    for row in reader:
        try:
            raw_track_id = str(
                row["track_id"]
            ).strip()

            generated = (
                _is_generated_track(
                    raw_track_id
                )
            )

            system_id = (
                _normalize_system_id(
                    raw_track_id
                )
            )

            member = _required_int(
                row["sample"]
            )

            forecast_hour = (
                _required_int(
                    row[
                        "lead_time_hours"
                    ]
                )
            )

            latitude = (
                _required_float(
                    row["lat"]
                )
            )

            longitude = (
                _required_float(
                    row["lon"]
                )
            )

            output.append(
                FNV3TrackPoint(
                    system_id=system_id,
                    member=member,
                    forecast_hour=forecast_hour,
                    latitude=latitude,
                    longitude=longitude,

                    max_wind_kt=_optional_float(
                        row.get(
                            "maximum_sustained_wind_speed_knots"
                        )
                    ),

                    mslp_hpa=_optional_float(
                        row.get(
                            "minimum_sea_level_pressure_hpa"
                        )
                    ),

                    # Numeric track IDs are cyclogenesis systems
                    # generated by the model itself.
                    genesis=generated,

                    # Named/basin-coded identifiers were already
                    # present at initialization or paired to an
                    # initialized system.
                    existing_storm=not generated,

                    radius_max_wind_km=_optional_float(
                        row.get(
                            "radius_of_maximum_winds_km"
                        )
                    ),

                    r34_ne_km=_optional_float(
                        row.get(
                            "radius_34_knot_winds_ne_km"
                        )
                    ),
                    r34_se_km=_optional_float(
                        row.get(
                            "radius_34_knot_winds_se_km"
                        )
                    ),
                    r34_sw_km=_optional_float(
                        row.get(
                            "radius_34_knot_winds_sw_km"
                        )
                    ),
                    r34_nw_km=_optional_float(
                        row.get(
                            "radius_34_knot_winds_nw_km"
                        )
                    ),

                    r50_ne_km=_optional_float(
                        row.get(
                            "radius_50_knot_winds_ne_km"
                        )
                    ),
                    r50_se_km=_optional_float(
                        row.get(
                            "radius_50_knot_winds_se_km"
                        )
                    ),
                    r50_sw_km=_optional_float(
                        row.get(
                            "radius_50_knot_winds_sw_km"
                        )
                    ),
                    r50_nw_km=_optional_float(
                        row.get(
                            "radius_50_knot_winds_nw_km"
                        )
                    ),

                    r64_ne_km=_optional_float(
                        row.get(
                            "radius_64_knot_winds_ne_km"
                        )
                    ),
                    r64_se_km=_optional_float(
                        row.get(
                            "radius_64_knot_winds_se_km"
                        )
                    ),
                    r64_sw_km=_optional_float(
                        row.get(
                            "radius_64_knot_winds_sw_km"
                        )
                    ),
                    r64_nw_km=_optional_float(
                        row.get(
                            "radius_64_knot_winds_nw_km"
                        )
                    ),
                )
            )

        except (
            KeyError,
            TypeError,
            ValueError,
        ):
            continue

    return output


def parse_weatherlab_cyclogenesis_file(path):
    """
    Parse a Weather Lab cyclogenesis CSV directly from disk.
    """

    path = Path(
        path
    )

    text = path.read_text(
        encoding="utf-8",
    )

    return (
        parse_weatherlab_cyclogenesis_csv(
            text
        )
    )


# ============================================================
# LEGACY GENERALIZED PAYLOAD SUPPORT
# ============================================================

def parse_generalized_tracks(payload):
    """
    Compatibility parser for the older generalized FNV3
    dictionary payload.
    """

    output = []

    for item in payload.get(
        "tracks",
        [],
    ):
        try:
            output.append(
                FNV3TrackPoint(
                    system_id=str(
                        item[
                            "system_id"
                        ]
                    ),
                    member=int(
                        item[
                            "member"
                        ]
                    ),
                    forecast_hour=int(
                        item[
                            "forecast_hour"
                        ]
                    ),
                    latitude=float(
                        item[
                            "latitude"
                        ]
                    ),
                    longitude=float(
                        item[
                            "longitude"
                        ]
                    ),
                    max_wind_kt=(
                        None
                        if item.get(
                            "max_wind_kt"
                        ) is None
                        else float(
                            item[
                                "max_wind_kt"
                            ]
                        )
                    ),
                    mslp_hpa=(
                        None
                        if item.get(
                            "mslp_hpa"
                        ) is None
                        else float(
                            item[
                                "mslp_hpa"
                            ]
                        )
                    ),
                    genesis=bool(
                        item.get(
                            "genesis",
                            False,
                        )
                    ),
                    existing_storm=bool(
                        item.get(
                            "existing_storm",
                            False,
                        )
                    ),
                )
            )

        except (
            KeyError,
            TypeError,
            ValueError,
        ):
            continue

    return output

# ============================================================
# WEATHERLAB ATCF COMPATIBILITY ENTRYPOINT
#
# FNV3 download code historically imports:
#
#     parse_weatherlab_atcf
#
# The generalized parser evolved and the implementation name
# changed. Preserve the public API here so downloader code does
# not depend on an internal parser-function name.
# ============================================================

def parse_weatherlab_atcf(text):
    """
    Parse the operational Weather Lab ATCF feed into
    FNV3TrackPoint objects.

    Storm identity and ensemble member identity are
    intentionally independent.

    system_id:
        Real ATCF cyclone identifier, e.g. AL04.

    member:
        FNV3 ensemble member, 0-49.
    """

    from fnv3_cyclone.download.atcf_client import (
        FNV3CycloneClient,
    )

    rows = (
        FNV3CycloneClient()
        .parse_atcf(text)
    )

    tracks = []

    for row in rows:

        system_id = row.get(
            "system_id"
        )

        member = int(
            row["member"]
        )

        # F000/F001/etc must NEVER become system IDs.
        if (
            system_id
            and str(system_id).upper().startswith("F")
        ):
            raise ValueError(
                "Invalid FNV3 system identity: "
                f"{system_id}. "
                "Member aid was incorrectly used as storm ID."
            )

        kwargs = {
            "system_id": system_id,
            "member": member,
            "forecast_hour": int(
                row["forecast_hour"]
            ),
            "latitude": float(
                row["latitude"]
            ),
            "longitude": float(
                row["longitude"]
            ),
        }

        # Different revisions of FNV3TrackPoint have used
        # slightly different optional field names. Inspect the
        # dataclass annotations so we only pass supported fields.

        annotations = getattr(
            FNV3TrackPoint,
            "__annotations__",
            {},
        )

        optional = {
            "cycle": row.get("cycle"),
            "basin": row.get("basin"),
            "storm_number": row.get(
                "storm_number"
            ),
            "aid": row.get("aid"),
            "max_wind_kt": row.get(
                "max_wind_kt"
            ),
            "min_pressure_hpa": row.get(
                "min_pressure_hpa"
            ),
            "existing_storm": True,
            "genesis": False,
        }

        for key, value in optional.items():

            if key in annotations:
                kwargs[key] = value

        tracks.append(
            FNV3TrackPoint(
                **kwargs
            )
        )

    return tracks


def filter_tracks_by_system(
    tracks,
    system_id=None,
):
    """
    Filter FNV3 tracks by real cyclone identity.

    Modes
    -----

    system_id="AL04"
        Return only AL04 while retaining every available
        FNV3 member.

    system_id=None
    system_id=""
    system_id="all"
        Generalized mode. Return every available system.

    No-storm-ID mode is intentional and is NOT an error.
    """

    if system_id in (
        None,
        "",
    ):
        return list(tracks)

    wanted = (
        str(system_id)
        .strip()
        .upper()
    )

    if wanted in {
        "ALL",
        "*",
        "NONE",
        "GENERALIZED",
    }:
        return list(tracks)

    return [
        point
        for point in tracks
        if (
            str(
                getattr(
                    point,
                    "system_id",
                    "",
                )
            )
            .strip()
            .upper()
            == wanted
        )
    ]

def filter_tracks_by_system(
    tracks,
    system_id=None,
):
    """
    Filter FNV3 tracks by real cyclone identity.

    Modes
    -----

    system_id="AL04"
        Return only AL04 while retaining every available
        FNV3 member.

    system_id=None
    system_id=""
    system_id="all"
        Generalized mode. Return every available system.

    No-storm-ID mode is intentional and is NOT an error.
    """

    if system_id in (
        None,
        "",
    ):
        return list(tracks)

    wanted = (
        str(system_id)
        .strip()
        .upper()
    )

    if wanted in {
        "ALL",
        "*",
        "NONE",
        "GENERALIZED",
    }:
        return list(tracks)

    return [
        point
        for point in tracks
        if (
            str(
                getattr(
                    point,
                    "system_id",
                    "",
                )
            )
            .strip()
            .upper()
            == wanted
        )
    ]
